### 전체 조회
GET http://localhost:3000/post

### 단건 조회
GET http://localhost:3000/post/1

### 검색
GET http://localhost:3000/post/search?title=Hello&authorName=John&tagNames=Nest&tagNames=JS

### 생성
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "Hello REST Client",
  "authorId": 1,
  "tagIds": [1, 2]
}

### 수정
PATCH http://localhost:3000/post/1
Content-Type: application/json

{
  "title": "Updated title"
}

### 삭제
DELETE http://localhost:3000/post/1
